---
- hosts: all
  user: docker
  sudo: yes
  tasks:
    - name: install nginx
      yum: name=nginx state=installed
    - name: set auto start nginx
      command: chkconfig nginx on
    - name: restart nginx
      command: service nginx restart
